version: "3.9"

services:
  api:
    build: ./api
    container_name: cognyte-api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - /app/build  
    working_dir: /app
    command: ./gradlew bootRun
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/eventsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - cognyte-network

  view:
    build: ./view
    container_name: cognyte-view
    ports:
      - "3000:3000"
    volumes:
      - ./view:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - api
    networks:
      - cognyte-network

  db:
    image: postgres:15
    container_name: cognyte-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cognyte-network

networks:
  cognyte-network:

volumes:
  pgdata:
